### PR TITLE
quick update to the retriever-site installation instructions

### PR DESCRIPTION
**Pull request by zhangcandrew**
updating the retriever-site's anaconda installation instructions due to changes in Anaconda's installation defaults.

### CODE REVIEW

**Comment by henrykironde** [comment]
Looks good to me

**Comment by henrykironde** [comment]
Perfect, I will let Ethan have a look at this since we may have to configure some DNS settings internally.

**Comment by henrykironde** [comment]
@ethanwhite #3, #2

**Comment by ethanwhite** [comment]
LGTM!

**Pull request merged**
